Add CONTRIBUTING and CODE_OF_CONDUCT.md
ComputerSocietyVITC/Question pull request #8
Opened 2023-10-05 18:25 UTC by JYunth

This DPR addresses #4 
Added in the basic templates for contribution and code of conduct, as seen on any normal open source repository.
@AbhijithGanesh if you have any organization specific contribution rules or code of conduct to be added, please let me know.

2023-10-05 18:28 UTC, AbhijithGanesh requested changes

2023-10-05 18:28 UTC, AbhijithGanesh commented on CONTRIBUTING.md
> +
Please add instructions about forking and branch naming conventions

2023-10-05 18:30 UTC, JYunth commented on CONTRIBUTING.md
> +
Okay, will do.

2023-10-05 19:02 UTC, JYunth commented
@AbhijithGanesh Take a look at the new additions. Is there anything else you require?

2023-10-06 07:26 UTC, AbhijithGanesh approved these changes

2023-10-06 07:27 UTC, merged